name: Trigger ASG Instance Refresh

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Good default

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364420385429:role/BSODAutoScalingRoles
          aws-region: ap-south-1

      - name: Start Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name BSOD-ASG \
            --strategy Rolling \
            --preferences '{
              "MinHealthyPercentage": 90,
              "InstanceWarmup": 300
            }'